### ISSUE TITLE
M+ Sort Group

### ISSUE THREAD

**Issue by tokeshlol** [Collabo93/SortGroup#3]
Hey,

Just letting you know: the Middle sorting for groups of 5 doesn't work (well it does - but it glitches often).  So at the beginning of the instance you'll set yourself up in the middle and have P1 P4 above and say P2 P3 below (or however it sorts it).  But as you go through the dungeon, it can flip and then all of the sudden P1 P2 are above, and P3 P4 are below.  It's almost like it happens on boss encounters or cut scenes, or just randomly.

Not a big thing as I know it's beta.  Just an FYI.

**Comment by Collabo93** [comment]
Old WoW Version - closed
