### ISSUE TITLE
Main Functionality not working - few errors here

### ISSUE THREAD

**Issue by ZetoxZ** [Collabo93/SortGroup#7]
Main functionality still not working. Here are my errors, hope they help! Thank you for all the effort here :)

-------------------------------------

2x SortGroup\SortGroup-5.1.05.lua:438: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@SortGroup\SortGroup-5.1.05.lua"]:438: in function <SortGroup\SortGroup.lua:435>
[string "@SortGroup\SortGroup-5.1.05.lua"]:567: in function <SortGroup\SortGroup.lua:550>

Locals:
(*temporary) = <table> {
UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:70
ERR_OUT_OF_CHI = "Not enough chi"
DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
}
MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
}
GetTrainerServiceTypeFilter = <function> defined =[C]:-1
UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
aux.frame11Shine10 = aux.frame11Shine10 {
}
SetTrainerServiceTypeFilter = <function> defined =[C]:-1
LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 788
SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 406
ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
PallyPowerC8P7BuffIcon = PallyPowerC8P7BuffIcon {
}
aux.frame12FlyoutBorderShadow = aux.frame12FlyoutBorderShadow {
}
CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
}
MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
}
ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
PVP_RANK_6_1 = "Corporal"
MultiBarLeftButton7 = MultiBarLeftButton7 {
}
InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
}
VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
}
MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
}
DetailsWindowOptionsBarTextEditorEntryNumberLines = DetailsWindowOptionsBarTextEditorEntryNumberLines {
}
OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
LoseControlOptionsPanelpetFriendlyDisarmDebuffText = LoseControlOptionsPanelpetFriendlyDisarmDebuffText {
}
MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
}
IsReferAFriendLinked = <function> defined =[C]:-1
MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:603
MANA = "Mana"
CHAT_CONFIG_OTHER_COMBAT = <table> {
}
CONSOLIDATED_BUFFS_PER_ROW = 4
BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 998
CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
}
LE_GAME_ERR_ONLY_ONE_QUIVER = 32
SpellButton6Cooldown = SpellButton6Cooldown {
}
PallyPowerBlessingsFramePlayer10Line5 = PallyPowerBlessingsFramePlayer10Line5 {
}
LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
Graphics_QualityText = Graphics_QualityText {
}
OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
}
VOICEMACRO_4_Sc_1_FEMALE = "Help me attack!"
JoinSkirmish = <function> defined =[C]:-1
Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
}
MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
}
BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
}
DMG_LCD = "DMG"
RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
}
PetPaperDollFrameTab3Right = PetPaperDollFrameTab3Right {
}
table: 00000241897CCA90Middle = table: 00000241897CCA90Middle {
}
Is64BitClient = <function> defined =[C]:-1
SecureCmdItemParse = <function> defined @FrameXML\ChatFrame.lua:1128
SLASH_STOPATTACK1 = "/stopattack"
MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
}
CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRai

----------------------------------------------------------------------

12x SortGroup\SortGroup-5.1.05.lua:171: attempt to call global 'CompactPartyFrame_SetFlowSortFunction' (a nil value)
[string "@SortGroup\SortGroup-5.1.05.lua"]:171: in function <SortGroup\SortGroup.lua:152>
[string "@SortGroup\SortGroup-5.1.05.lua"]:272: in function <SortGroup\SortGroup.lua:249>
[string "@SortGroup\SortGroup-5.1.05.lua"]:561: in function <SortGroup\SortGroup.lua:550>

Locals:
CRFSort_BottomUpwards = <function> defined @SortGroup\SortGroup.lua:157
(*temporary) = nil
(*temporary) = <function> defined @SortGroup\SortGroup.lua:157
(*temporary) = "attempt to call global 'CompactPartyFrame_SetFlowSortFunction' (a nil value)"
internValues_DB = <table> {
showChatMessages = false
firstLoad = true
}
savedValues_DB = <table> {
Top = false
BottomAscending = true
ChatMessagesOn = true
Middle = false
Bottom = true
}
ColorText = <function> defined @SortGroup\SortGroup.lua:67
L = <table> {
SortGroup_sort_top_ascending_output = "SortGroup: Active with - Top, Ascending"
SortGroup_sort_no_output = "SortGroup: Sort function isn't active"
SortGroup_Main_cb_Descending_ToolTip = "Party 1-4 are sorted descending"
SortGroup_Main_cb_Top_ToolTip = "You are on top of your Group"
SortGroup_Main_cb_ChatMessagesOn_ToolTip = "Chat Messages on/off"
SortGroup_Option_cb_ChatMessagesOn_Text = "Chat messages"
SortGroup_Main_cb_Bottom_ToolTip = "You are on bottom of your Group"
SortGroup_Main_cb_Ascending_Text = "Ascending"
SortGroup_sort_bottom_descending_output = "SortGroup: Active with - Bottom, Descending"
SortGroup_enter_editMode = "SortGroup: Please reload your UI"
SortGroup_in_combat_options_output = "SortGroup: Leave combat to change options"
SortGroup_Main_cb_Top_Text = "Player on Top"
SortGroup_sort_top_descending_output = "SortGroup: Active with - Top, Descending"
SortGroup_sort_chat_Messages_On_output = "SortGroup: Chat Messages are on"
SortGroup_Main_cb_Middle_ToolTip = "[Experimental]
You are in the middle of your Group

Note:
This option makes only sense in an arena environment"
SortGroup_sort_top_party2_output = "SortGroup: Active sorted with - Party2, top"
SortGroup_sort_bottom_ascending_output = "SortGroup: Active with - Bottom, Ascending"
SortGroup_Main_cb_Party2Top_Text = "Party2 on Top"
SortGroup_sort_top_party1_output = "SortGroup: Active with - Party1, top"
SortGroup_Main_cb_Party2Top_ToolTip = "Party2 is on top and Party1 is on the bottom of your group"
SortGroup_Main_cb_Ascending_ToolTip = "Party 1-4 are sorted ascending"
SortGroup_Main_cb_Party1Top_Text = "Party1 on Top"
SortGroup_Main_cb_Bottom_Text = "Player on Bottom"
SortGroup_Main_cb_Party1Top_ToolTip = "Party1 is on top and Party2 is on the bottom of your group"
SortGroup_Main_cb_Middle_Text = "Player in the Middle"
SortGroup_Main_cb_Descending_Text = "Descending"
}

---------------------------------------------------------------------------

8x SortGroup\SortGroup-5.1.05.lua:202: attempt to call global 'CompactPartyFrame_SetFlowSortFunction' (a nil value)
[string "@SortGroup\SortGroup-5.1.05.lua"]:202: in function <SortGroup\SortGroup.lua:183>
[string "@SortGroup\SortGroup-5.1.05.lua"]:269: in function <SortGroup\SortGroup.lua:249>
[string "@SortGroup\SortGroup-5.1.05.lua"]:561: in function <SortGroup\SortGroup.lua:550>

Locals:
CRFSort_BottomDownwards = <function> defined @SortGroup\SortGroup.lua:188
(*temporary) = nil
(*temporary) = <function> defined @SortGroup\SortGroup.lua:188
(*temporary) = "attempt to call global 'CompactPartyFrame_SetFlowSortFunction' (a nil value)"
internValues_DB = <table> {
showChatMessages = false
firstLoad = true
}
savedValues_DB = <table> {
Top = false
BottomAscending = false
ChatMessagesOn = true
BottomDescending = true
Middle = false
Bottom = true
}
ColorText = <function> defined @SortGroup\SortGroup.lua:67
L = <table> {
SortGroup_sort_top_ascending_output = "SortGroup: Active with - Top, Ascending"
SortGroup_sort_no_output = "SortGroup: Sort function isn't active"
SortGroup_Main_cb_Descending_ToolTip = "Party 1-4 are sorted descending"
SortGroup_Main_cb_Top_ToolTip = "You are on top of your Group"
SortGroup_Main_cb_ChatMessagesOn_ToolTip = "Chat Messages on/off"
SortGroup_Option_cb_ChatMessagesOn_Text = "Chat messages"
SortGroup_Main_cb_Bottom_ToolTip = "You are on bottom of your Group"
SortGroup_Main_cb_Ascending_Text = "Ascending"
SortGroup_sort_bottom_descending_output = "SortGroup: Active with - Bottom, Descending"
SortGroup_enter_editMode = "SortGroup: Please reload your UI"
SortGroup_in_combat_options_output = "SortGroup: Leave combat to change options"
SortGroup_Main_cb_Top_Text = "Player on Top"
SortGroup_sort_top_descending_output = "SortGroup: Active with - Top, Descending"
SortGroup_sort_chat_Messages_On_output = "SortGroup: Chat Messages are on"
SortGroup_Main_cb_Middle_ToolTip = "[Experimental]
You are in the middle of your Group

Note:
This option makes only sense in an arena environment"
SortGroup_sort_top_party2_output = "SortGroup: Active sorted with - Party2, top"
SortGroup_sort_bottom_ascending_output = "SortGroup: Active with - Bottom, Ascending"
SortGroup_Main_cb_Party2Top_Text = "Party2 on Top"
SortGroup_sort_top_party1_output = "SortGroup: Active with - Party1, top"
SortGroup_Main_cb_Party2Top_ToolTip = "Party2 is on top and Party1 is on the bottom of your group"
SortGroup_Main_cb_Ascending_ToolTip = "Party 1-4 are sorted ascending"
SortGroup_Main_cb_Party1Top_Text = "Party1 on Top"
SortGroup_Main_cb_Bottom_Text = "Player on Bottom"
SortGroup_Main_cb_Party1Top_ToolTip = "Party1 is on top and Party2 is on the bottom of your group"
SortGroup_Main_cb_Middle_Text = "Player in the Middle"
SortGroup_Main_cb_Descending_Text = "Descending"
}

**Comment by ZetoxZ** [comment]
4x SortGroup\SortGroup-5.1.05.lua:438: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@SortGroup\SortGroup-5.1.05.lua"]:438: in function <SortGroup\SortGroup.lua:435>
[string "@SortGroup\SortGroup-5.1.05.lua"]:567: in function <SortGroup\SortGroup.lua:550>

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 aux.frame11Shine10 = aux.frame11Shine10 {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 788
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 406
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 PallyPowerC8P7BuffIcon = PallyPowerC8P7BuffIcon {
 }
 aux.frame12FlyoutBorderShadow = aux.frame12FlyoutBorderShadow {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 DetailsWindowOptionsBarTextEditorEntryNumberLines = DetailsWindowOptionsBarTextEditorEntryNumberLines {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 LoseControlOptionsPanelpetFriendlyDisarmDebuffText = LoseControlOptionsPanelpetFriendlyDisarmDebuffText {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:603
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 CONSOLIDATED_BUFFS_PER_ROW = 4
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 998
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 PallyPowerBlessingsFramePlayer10Line5 = PallyPowerBlessingsFramePlayer10Line5 {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 VOICEMACRO_4_Sc_1_FEMALE = "Help me attack!"
 JoinSkirmish = <function> defined =[C]:-1
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 PetPaperDollFrameTab3Right = PetPaperDollFrameTab3Right {
 }
 table: 00000241897CCA90Middle = table: 00000241897CCA90Middle {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML\ChatFrame.lua:1128
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRai

**Comment by Collabo93** [comment]
Seems odd that he cant find 'CompactPartyFrame_SetFlowSortFunction'. Does this also happen with only SortGroup enabled? If this issue persists, can you try setting the value 'RaidProfileBlockInCombat'  in line 27 to false? This deactivates all hookes.

**Comment by Collabo93** [comment]
Closing, this version was most likely used in classic
