### ISSUE TITLE
Addon not loading

### ISSUE THREAD

**Issue by aza547** [Collabo93/SortGroup#9]
Hi, love the addon and have been using it for years.

I have installed the latest version and it shows up in my list of addons:

![image](https://user-images.githubusercontent.com/32389325/206807095-6ab6746d-e132-40c6-9c32-c5a8b426dc4a.png)

but `/sortgroup` returns a help message as if the addon isn't installed and it also doesn't appear in the interface pane:

![image](https://user-images.githubusercontent.com/32389325/206807189-4bf6e3ea-9474-479d-9889-628b0bdcf077.png)

Is this expected currently? Saw some recent commits that looked like things might be a bit broken.

Thanks

**Comment by Collabo93** [comment]
Thats odd, do you get any errors? The newest version is not stable but should load.

**Comment by aza547** [comment]
Didn't see anything with bugsack at the time, but I've just re-installed at 1.0.2 and seems to be working nicely. 

Thanks again.
